config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index,:new,:create,:show]

  resources :users, only: %i[show] do
    member do
      post :followings, :followers
    end
    resources :relationships, only: [:create]
  end

  resources :relationships, only: [:destroy]

  resources :tweets, only: [:index, :create] do
    resources :likes, only: [:create, :destroy]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :tweet_id }

  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  validates :text, presence: true, length: { maximum: 255 }

  def likes
    Tweet.joins(:likes).where(id: id).count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, foreign_key: :author_id, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships

  has_many :likes, dependent: :destroy

  has_one_attached :profile_pic
  has_one_attached :cover_pic

  validates :username, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :fullname, presence: true, length: { maximum: 100 }

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def not_following
    User.where.not(id: followings.pluck(:id)).where.not(id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  before_action :authenticate_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate_user
    redirect_to new_session_path, alert: 'Please signup or login to continue' unless logged_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(tweet_id: params[:tweet_id])

    redirect_to tweets_path if @like.save
  end

  def destroy
    like = Like.find_by(id: params[:id], user: current_user, tweet_id: params[:tweet_id])
    like.destroy
    redirect_to tweets_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    flash.now[:notice] = 'testing testing'
    redirect_to tweets_path
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow(user)

    redirect_to tweets_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, only: %i[new create]
  def new; end

  def create
    @user = User.find_by(username: params[:username])
    if @user
      session[:user_id] = @user.id
      flash[:success] = 'Logged in successfully'
      redirect_to tweets_path(@user)
    else
      flash.now[:notice] = 'Please enter valid username'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged Out'
    redirect_to new_session_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.includes(:author).ordered_by_most_recent
    @users = User.all.ordered_by_most_recent
    @tweet = Tweet.new
    @follow_suggestions = current_user.not_following.ordered_by_most_recent
  end

  def new
    @tweet = current_user.tweets.build
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      flash[:notice] = 'New tweet created'
      redirect_to tweets_path
    else
      render :new
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:author_id, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: %i[new create]
  def index
    @users = User.all.ordered_by_most_recent
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Sign Up Successfully'
      redirect_to tweets_path
    else
      flash[:notice] = 'Username already exists OR Username is blank'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image, :profile_pic, :cover_pic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_for(user)
    encoded_name = ERB::Util.url_encode(user.fullname)
    src = "https://ui-avatars.com/api/?name=#{encoded_name}&format=svg&background=DBEAFE"

    content_tag(:img, '', src: src, alt: user.fullname, class: 'rounded-circle')
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_or_dislike_btn(tweet)
    like = Like.find_by(tweet: tweet, user: current_user)
    if like
      link_to('Dislike!', tweet_like_path(id: like.id, tweet_id: tweet.id), method: :delete)
    else
      link_to('Like!', tweet_likes_path(tweet_id: tweet.id), method: :post)
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  def follow_button(user)
    return if current_user == user

    if current_user.followings.exists?(user.id)
      form_with url: relationship_path(user), method: :delete do |form|
        form.submit 'Unfollow',
                    class: ' px-4 py-1 bg-primary text-light rounded-pill text-red-500 border rounded-full btn-sm'
      end
    else
      form_with url: user_relationships_path(user) do |form|
        form.submit 'Follow',
                    class: ' px-4 py-1 bg-primary text-light rounded-pill text-red-500 border btn-sm rounded-full '
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def likes_count(tweet)
    tweet.likes
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def cover_picture(user)
    if user.cover_pic.attached?
      image_tag user.cover_pic, class: 'w-100 p-img'
    else
      image_tag 'book2.png', class: 'w-100 p-img'
    end
  end

  def profile_picture(user)
    if user.profile_pic.attached?
      image_tag user.profile_pic, class: 'profile'
    else
      avatar_for(user)
    end
  end

  def tag_picture(user)
    if user.profile_pic.attached?
      image_tag user.profile_pic, class: 'tag_profile'
    else
      avatar_for(user)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TwitterRedesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  </head>

  <body class="main">
    <%= yield %>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>

app/views/tweets/_feed.html.erb
<% @tweets.each do |tweet| %>
   <div class="d-block index-feed">
   <div class="d-flex justify-content-between border-bottom pb-2">
   <div class="d-flex align-items-center">
      <span class="avatar"><%= tag_picture(tweet.author)%></span>
      <p class="pl-2 pt-3"><%= tweet.author.username %></p>
	</div>
	<p><%= tweet.created_at.strftime("#{tweet.created_at.day.ordinalize} %B %Y") %></p>
   </div>

	<p><%= tweet.text %></p>
   <%=like_or_dislike_btn(tweet)%>
   <span class="text-primary"><%= likes_count(tweet) %></span>
	</div>
<% end %>

app/views/tweets/_form.html.erb
<div class="fill_form p-4">
<div class="tweet_header text-dark d-flex">
   <p class="">TWEET SOMETHING</p>
</div>
<%= form_with model: @tweet do |f| %>
    <%= f.text_area :text, class: "form-control rounded-pill", placeholder: "Let's Tweet Something nice"%>
    <br>
    <%= f.submit class: "btn btn-primary btn-sm" %>
<% end %>
</div>

app/views/tweets/_left_nav.html.erb
<div class="left_nav text-secondary  px-2 pt-3">
      <div class="d-flex text-center mx-auto align-items-center justify-content-around">
       <div class="profile-users">
	   <%= profile_picture(current_user) %>
		</div>
		<div class="pl-1">
		  <%= current_user.fullname %>
		</div>
	  </div>
		<div class="d-block pt-4">
		  <%= render 'tweets/stat' %>
		  <strong class="pr-3 ml-2"><i class="fa fa-home"></i><%= link_to 'Homepage', tweets_path, class: "text-secondary pl-2"%></strong><br />
		  <br>
	      <strong class="pr-3 ml-2"><i class="fa fa-user"></i><%= link_to 'Profile', current_user, class: "text-secondary pl-2"%></strong><br />
        </div>
</div>

app/views/tweets/_stat.html.erb
<% @user ||= current_user %>
<div class="stats d-flex justify-content-between text-center mx-2">
	<div id="following" class="stat">
	 <p class="font-weight-bold"><%= @user.followings.count %></p>
      <p class="font-weight-bold">following</p>
	</div>
	</a>
	<div id="followers" class="stat">
	<p class="font-weight-bold"><%= @user.followers.count %></p>
	<p class="font-weight-bold">followers</p>
	</div>
	</a>
</div>

app/views/tweets/_top_nav.html.erb
<div class="d-flex justify-content-between top_nav sticky-top">

      <%=  image_tag("book_logo.png", :alt => "book_image", class: "h-100 w-15") %>

   <p class="d-flex justify-content-end pt-4">
	  <strong ><%= link_to current_user.fullname, current_user, class: "text-light pr-3" %></strong><br />
	  <strong ><%= link_to 'Log out', session_path('current_user'), class: "text-light pr-4", method: :delete %></strong>
	</p>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="mt-2">
<h4 class="text-muted mx-3 pt-2">who to follow</h4>
<hr class="mx-3">
<% @follow_suggestions.each do |user| %>
    <div class="d-flex justify-content-center">
    <span class="avatar"><%= tag_picture(user)%></span>
    <div class="col-6">
      <span>
      <strong><%=link_to user.fullname, user_path(user)%></strong>
      <br>
      <small>@<%= user.username %></small>
      </span>
    </div>
      <div class="col-4">
        <%= follow_button(user) %>
      </div>
    </div>
    <hr class="mx-3">
<%end%>
</div>

app/views/tweets/index.html.erb
	<div class="d-flex flex-row no-gutters main">

		
		  <%= render 'left_nav' %>
		

		<div class="right_side w-100">
		 <%= render 'top_nav' %>
		  <div class="d-flex flex-row no-gutters">
		   <div class="col-8">
		   <span class="border-bottom text-dark p-2 border-primary">Tweet</span><br />
		   <div class="content mx-4 mt-4">
		   <div class="bg-white index-form in-content">
		   <%= render 'form' %>
		   </div>

		   <div class="bg-white mt-3 in-content rounded">
		     <%= render 'feed' %>
		   </div>
		   </div>
		   </div>
		   <div class="col-4">
		   <div class="bg-white rounded m-3 in-content">
		    <%= render 'who-to-follow' %>
		   </div>
		   </div>
		  </div>
		</div>

	</div>

app/views/tweets/new.html.erb
<div class="col-2 position-fixed bg-success" style="height: 100vh;">
		  <%= render 'left_nav' %>
		</div>

		<div class="col-10 bg-secondary">
		<h1>all tweets</h1>
		<% @tweets.each do |t| %>
		<%= t.author.username %>
		<%= t.text %>
		<% end %>
		</div>

app/views/users/_form.html.erb
<section class="sec">
  <div class="imgBx">
    <%=  image_tag("book1.png", :alt => "book_image", class: "img") %>
    <div class="in-imgBx">
      <h2 class="font-weight-bolder font-weight-bolder font-italic">Welcome to twitter for books</h2>
      <p class="text-center">The kind of books you read says alot about you</p>
    </div>
  </div>
  <div class="contentBx">
    <div class="formBx">
    <%= form_with model: @user do |form| %>
      <h2>Sign Up</h2>
      <div class="inputBx">
        <span><%= form.label :username, "Username:" %></span>
        <%= form.text_field :username, class:"input" %><br/><br/>
      </div>
      <div class="inputBx">
        <span><%= form.label :fullname, "Fullname:" %></span>
        <%= form.text_field :fullname, class:"input" %><br/><br/>
      </div>
      <div class="inputBx">
        <span><%= form.label :profile_pic, "Profile Photo:" %></span>
        <%= form.file_field :profile_pic, class:"input" %><br/><br/>
      </div>
      <div class="inputBx">
        <span><%= form.label :cover_pic, "Cover Photo" %></span>
        <%= form.file_field :cover_pic, class:"input" %><br/><br/>
      </div>
      <div class="inputBx">
        <%= form.submit 'Sign Up', class:"input" %>
      </div>
      <div class="inputBx d-inline">
        <p class="pt-2 text-center">Already have an account? <%= link_to 'Login', new_session_path %></p>
      </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/new.html.erb
 
<%= render 'form' %>

app/views/users/show.html.erb
	<div class="d-flex flex-row no-gutters">

		<div class="">
		  <%= render 'tweets/left_nav' %>
		</div>

		<div class="right_side w-100">
		 <%= render 'tweets/top_nav' %>
		  <div class="d-flex flex-row no-gutters">
		   <div class="col-8">
          

		   <div class="w-100">
			<%= cover_picture(@user) %>
		   </div>
           
		  
		   <span class="border-bottom text-dark p-2 border-primary">Tweet</span><br />
		
		

				<div class="bg-white mt-4 mx-4 rounded in-content">
					<% @user.tweets.each do |t| %>
						<div class="d-block border-bottom p-4">
						<div class="d-flex justify-content-between border-bottom pb-2">
							<div class="profile-users d-flex ">
								<span class="avatar"><%= tag_picture(t.author)%></span>
								<p class="pl-2 pt-3"><%= t.author.username %></p>
							</div>
							<p><%= t.created_at.strftime("#{t.created_at.day.ordinalize} %B %Y") %></p>
						</div>

							<p><%= t.text %></p>
							</div>
						<% end %>
				</div>
		   </div>
		   <div class="col-4">
		   <div class="bg-white rounded m-3 text-center in-content">
		           <div class="pt-2">
                        <%= profile_picture(@user) %>
                        <p class="">
                            <strong><%= @user.fullname.upcase %></strong><br />
                            <small>@<%= @user.username %></small>
                        </p>
					</div>
				<div>
				  <%= follow_button(@user)%>
				</div>
                <div class="followings border-top border-bottom">
                <div class="d-flex justify-content-center">
                    <div class="px-3">
					    <p class=""><%=@user.tweets.count%></p>
                        <p class="">Tweets</p>
                    </div>
                    <div class="px-3">
					<p class=""><%=@user.followings.count%></p>
                        <p class="">Followings</p>
                    </div>
                    <div class="px-3">
					    <p class=""><%=@user.followers.count%></p>
                        <p class="">Followers</p>
                    </div>
                </div>
                </div>
				 <div class="mt-4">
                    <p class="heading text-uppercase">Followed by</p>
					<hr>
                    <%@user.followers.each do |follower|%>
					  <div class="">
					  <p><%= follower.fullname%></p>
					  <small>@<%= follower.username %></small>
						  <hr>
                    <%end%>
                </div>
		   </div>
		  </div>
		</div>

	</div>